---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.neo4j.fullName $ }}
  labels:
    {{- (tpl ($.Values.neo4j.commonLabels | toYaml ) $) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- (tpl ($.Values.neo4j.commonLabels | toYaml ) $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- (tpl ($.Values.neo4j.commonLabels | toYaml ) $) | nindent 8 }}
    spec:
      securityContext:
        {{- include "common.security.podSecurityContext.restricted" dict | nindent 8 }}

      containers:
      - name: neo4j
      {{- with $.Values.neo4j.image }}
        image: {{ tpl (printf "%s:%s" .repository .tag) $ }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.neo4j.httpPort }}
            name: http
        envFrom:
        - configMapRef:
            name: {{ tpl .Values.neo4j.fullName $ }}
        securityContext:
          {{- include "common.security.containerSecurityContext.restricted" dict | nindent 10 }}
