services:
  neo4j:
    image: neo4j:5-community
    # comment the "ports" section if you don't want users to access neo4j UI
    ports:
      - "${NEO4J_HTTP_PORT}:7474" # HTTP port
      - "${NEO4J_BOLT_PORT}:7687" # BOLT port
    expose:
      - "${NEO4J_BOLT_PORT}"
      - "${NEO4J_HTTP_PORT}"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
      - ./backups:/backups
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      # use the following line instead to disable authentication
      # - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=${NEO4J_HEAP_INITIAL}
      - NEO4J_server_memory_heap_max__size=${NEO4J_HEAP_MAX}
      - NEO4J_server_memory_pagecache_size=${NEO4J_PAGECACHE_SIZE}
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:7474" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - ikg-network
    profiles:
      - neo4j
networks:
  ikg-network:
    driver: bridge