---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.crisalidBus.fullName $ }}
  labels:
    {{- (tpl ($.Values.crisalidBus.commonLabels | toYaml ) $) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- (tpl ($.Values.crisalidBus.commonLabels | toYaml ) $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- (tpl ($.Values.crisalidBus.commonLabels | toYaml ) $) | nindent 8 }}
    spec:
      securityContext:
        {{- include "common.security.podSecurityContext.restricted" dict | nindent 8 }}

      containers:
      - name: crisalid-bus
      {{- with $.Values.crisalidBus.image }}
        image: {{ tpl (printf "%s:%s" .repository .tag) $ }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.crisalidBus.httpPort }}
          name: http
        - containerPort: {{ .Values.crisalidBus.amqPort }}
          name: amq
        envFrom:
        - configMapRef:
            name: {{ tpl .Values.crisalidBus.fullName $ }}
        - secretRef:
            name: {{ tpl .Values.crisalidBus.fullName $ }}
        securityContext:
          {{- include "common.security.containerSecurityContext.restricted" dict | nindent 10 }}
        livenessProbe:
        {{- .Values.crisalidBus.livenessProbe | toYaml | nindent 10 }}
        readinessProbe:
        {{- .Values.crisalidBus.readinessProbe | toYaml | nindent 10 }}
        volumeMounts:
        - name: definitions
          mountPath: {{ .Values.crisalidBus.definitionsFile }}
      volumes:
      - name: definitions
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{printf "%s-definitions" (tpl .Values.crisalidBus.fullName $) }}
